site_name: CruxGen
site_description: LLM-ready datasets. Straight from the source.
site_author: Prathamesh Kulkarni
site_url: https://github.com/VajraM-dev/CruxGen
repo_url: https://github.com/VajraM-dev/CruxGen.git

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - content.code.select
    - content.code.annotate

nav:
  - Home: index.md
  - API Reference: 
      - Main App: api_routers/main.md
      - Document Management: api_routers/document_router.md
      - Chunking Router: api_routers/chunk_management.md
      - QA Router: api_routers/qa_management.md
  - SDK Reference: sdk.md
  - Future Work: future_work.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kprathamesh/
    - icon: fontawesome/brands/github
      link: https://github.com/VajraM-dev

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search